### ISSUE TITLE
Resource planner 5g slicing modeling and inclusion in planning

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#67]
**Is your feature request related to a problem? Please describe.**
5G slicing support for middleware in terms of modeling in redis, in middleware and how planner and dedicated 5g policies apply.

**Additional context**
This is required for the next integration meeting in 2023. Get input from networking and 5g partners to model this.

**Comment by adrianLIrobotics** [comment]
[5gSlicing.docx](https://github.com/5G-ERA/middleware/files/10237947/5gSlicing.docx)

**Comment by Artonus** [comment]
Moved to v0.5 Milestone, as it will be a crucial part of testing the testbed and slice integration.

The slices provided are:
* default
* ultra-reliable and low latency (URLLC)
The assignment of the slice could be controlled by policies. For example, we could have Instance-scoped policies that would alter the planning process for Instances. If the URLLC network policy is specified for the Instance, the Resource Planner will ask Slice Manager to assign the specific robot to the URLLC Slice.

This issue is associated with the `Policies` development (#124)
