### ISSUE TITLE
⚠️ DashboardService _taskRepository.GetAllAsync(); gets ALL Tasks with actionSequnece Null

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#93]
**Describe the bug**
In the dashboardService class, the function GetActionSequenceAsync(), the line:
var tasks = await _taskRepository.GetAllAsync();

gets a list of tasks objects which actionSequence is always null.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Branch: AL/EndpointsDashboard_Middleware

1. Launch redis interface
2. Run: "/api/v1/actionSequence"
3. Put stop point in code in line --> var tasks = await _taskRepository.GetAllAsync();
4. See the actionSequence attribute of all obkects in result

**Expected behavior**
The tasks should have loaded their action Sequence.

**Screenshots**
![image](https://user-images.githubusercontent.com/26432703/211270903-1d54dd36-08a0-4e15-8dc2-86aed54fd53d.png)

**Additional context**
In Redis there are some tasks with no actions, but NOT ALL of them :)
This issue was discovered in the QA of Dasboard

**Comment by Artonus** [comment]
@adrianLIrobotics it is not a bug. By design, we don't store the action sequences together with the TaskModel. As the Action sequence was supposed to be constructed dynamically, there was no reason to store them together. To retrieve the ActionSequence you have to call Redis Graph for the relations from the specific task. Only then you will retrieve the desired actions.
